services:
  - type: web
    runtime: node
    name: app
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm run build && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
